- name: Deploy Dockerized Application
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker Hub
      shell: echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      register: docker_login_result
      failed_when: docker_login_result.rc != 0
      no_log: true  # Hide the output to avoid showing sensitive information

    - name: Stop and remove existing container (if running)
      shell: |
        docker stop demo-app || true
        docker rm demo-app || true
      ignore_errors: yes

    - name: Pull Docker image
      shell: docker pull {{ docker_image }}

    - name: Run Docker container
      shell: docker run -d --name demo-app -p 8083:8080 {{ docker_image }}

    - name: Verify the container is running
      shell: docker ps | grep demo-app
      register: container_status

    - name: Display container status
      debug:
        msg: "Docker container 'demo-app' status: {{ container_status.stdout_lines }}"
