- name: Deploy Dockerized Application
  hosts: localhost
  become: yes
  tasks:
    # Ensure Docker is installed
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Ensure Docker service is running
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      shell: |
        echo "{{ docker_password | quote }}" | docker login -u "{{ docker_username | quote }}" --password-stdin
      register: docker_login_result
      failed_when: docker_login_result.rc != 0
      no_log: true  # Hide sensitive info

    # Build the Docker image
    - name: Build Docker image
      shell: |
        docker build -t {{ docker_image }} .
      args:
        chdir: /path/to/your/dockerfile  # Replace with the correct path where your Dockerfile is located

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      shell: docker push {{ docker_image }}

    # Check if port 8083 is in use
    - name: Check if port 8083 is in use
      shell: lsof -i :8083
      register: port_check
      failed_when: false

    # Kill the process using port 8083 if it exists
    - name: Kill the process using port 8083 (if any)
      shell: "kill -9 $(lsof -ti :8083)"
      when: port_check.stdout != ""
      ignore_errors: yes

    # Pause for 3 seconds
    - name: Wait for 3 seconds to ensure port is released
      pause:
        seconds: 3

    # Stop and remove the existing Docker container if it is running
    - name: Stop and remove existing container (if running)
      shell: |
        docker stop demo-app || true
        docker rm demo-app || true
      ignore_errors: yes

    # Pull the latest Docker image from Docker Hub (freshly pushed image)
    - name: Pull Docker image
      shell: docker pull {{ docker_image }}

    # Run the new Docker container
    - name: Run Docker container
      shell: docker run -d --name demo-app -p 8083:8080 {{ docker_image }}

    # Verify that the Docker container is running
    - name: Verify the container is running
      shell: docker ps | grep demo-app
      register: container_status
      failed_when: container_status.rc != 0

    # Display the status of the running Docker container
    - name: Display container status
      debug:
        msg: "Docker container 'demo-app' is running. Status:\n{{ container_status.stdout_lines }}"
