apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: my-app         # match Service label
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http          #  match port name in Service
      path: /actuator/prometheus
      interval: 15s
