apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-deployment
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m
  path: "./nginx"  # Now pointing to the nginx directory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
