apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-pvc
  namespace: autopilot-cluster-sm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
