apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo-cluster
spec:
  type: NodePort  
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
