name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          exit-code: "1"
          severity: "CRITICAL"
          ignore-unfixed: true  # Ignore vulnerabilities that have no fixed version
          format: "table"
          timeout: "5m"

      - name: Pull Docker Image
        run: docker pull sushmamounika/my-repo-sm:latest || echo "Image not found"

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "sushmamounika/my-repo-sm:latest"
          exit-code: "1"
          severity: "CRITICAL"
          ignore-unfixed: true
          format: "table"
          timeout: "5m"
